image: registry.gitlab.com/noritakaizumi/my-portfolio/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

hugo:
  stage: build
  before_script:
    - npm ci
    - git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git
    - rm -r my-portfolio-posts/.git
    - mv my-portfolio-posts content
  script:
    # https://github.com/gohugoio/hugo/issues/8025
    - |
      env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_REPOID=$GISCUS_REPOID \
        env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_CATEGORY=$GISCUS_CATEGORY \
        env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_CATEGORYID=$GISCUS_CATEGORYID \
        hugo --logLevel info --minify --cleanDestinationDir --gc
  artifacts:
    paths:
      - public

e2e:
  stage: test
  image: registry.gitlab.com/noritakaizumi/my-portfolio/e2e
  dependencies:
    - hugo
  before_script:
    - . /root/.profile
  script:
    - npm run test
    - test -z "$(find public/ -type d -name '.git')"
    - test -z "$(find public/images/ -type f -exec stat -c '%s' {} \; | grep '^0$')"
  artifacts:
    when: always
    expose_as: "e2e test results"
    expire_in: 7 days
    paths:
      - ./test-results/e2e-test-results.xml
    reports:
      junit:
        - ./test-results/e2e-test-results.xml

# for GitLab Pages
pages:
  stage: deploy
  dependencies:
    - hugo
    - e2e
  script:
    - "true"
  artifacts:
    paths:
      - public
  only:
    - master
