# This file is a template, and might need editing before it works on your project.
---
image: registry.gitlab.com/noritakaizumi/my-portfolio/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.npm_ci:
  script:
    - npm ci

.fetch_posts:
  script:
    - "git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git || exit 1"
    - "rm -rf my-portfolio-posts/.git || exit 1"
    - "mv my-portfolio-posts content || exit 1"

.hugo_build:
  script:
    # https://github.com/gohugoio/hugo/issues/8025
    - |
      env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_REPOID=$GISCUS_REPOID \
        env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_CATEGORY=$GISCUS_CATEGORY \
        env HUGO_PARAMS_FEATURES_COMMENT_SERVICES_GISCUS_CATEGORYID=$GISCUS_CATEGORYID \
        hugo --logLevel info --minify --cleanDestinationDir --gc

hugo:
  stage: build
  script:
    - !reference [.npm_ci, script]
    - !reference [.fetch_posts, script]
    - !reference [.hugo_build, script]
  artifacts:
    paths:
      - public
  except:
    - master

# for GitLab Pages
pages:
  stage: build
  script:
    - !reference [.npm_ci, script]
    - !reference [.fetch_posts, script]
    - !reference [.hugo_build, script]
  artifacts:
    paths:
      - public
  only:
    - master

e2e:
  stage: test
  image: registry.gitlab.com/noritakaizumi/my-portfolio/e2e
  dependencies:
    - hugo
  before_script:
    - . /root/.profile
  script:
    - npm run test
    # check there is no empty images
    - test $(find public/images/ -type f -exec stat -c '%s' {} \; | grep '^0$' | wc -l) = 0 || exit 1
  artifacts:
    when: always
    paths:
      - ./test-results/e2e-test-results.xml
    reports:
      junit:
        - ./test-results/e2e-test-results.xml
