# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo:0.112.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update
  - apk --no-cache add git
  - "command -v git || exit 1"

.npm_ci:
  script:
    - npm ci

hugo:
  stage: build
  script:
    - !reference [.npm_ci, script]
    - "git --version || exit 1"
    - "git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git || exit 1"
    - "rm -rf my-portfolio-posts/.git || exit 1"
    - "mv my-portfolio-posts content || exit 1"
    # https://github.com/gohugoio/hugo/issues/8025
    - hugo --verbose --minify --cleanDestinationDir --gc
    # check there is no empty images
    - test $(find public/images/ -type f -exec stat -c '%s' {} \; | grep '^0$' | wc -l) = 0 || exit 1
  except:
    - master

pages:
  stage: build
  script:
    - !reference [.npm_ci, script]
    - "git --version || exit 1"
    - "git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git || exit 1"
    - "rm -rf my-portfolio-posts/.git || exit 1"
    - "mv my-portfolio-posts content || exit 1"
    # https://github.com/gohugoio/hugo/issues/8025
    - hugo --verbose --minify --cleanDestinationDir --gc
    # check there is no empty images
    - test $(find public/images/ -type f -exec stat -c '%s' {} \; | grep '^0$' | wc -l) = 0 || exit 1
  artifacts:
    paths:
      - public
  only:
    - master
