# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo:0.109.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update
  - apk --no-cache add git
  - "command -v git || exit 1"

hugo:
  stage: build
  script:
    - "git --version || exit 1"
    - "git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git || exit 1"
    - "rm -rf my-portfolio-posts/.git || exit 1"
    - "mv my-portfolio-posts content || exit 1"
    - hugo --gc --ignoreCache --verbose
  except:
    - master

pages:
  stage: build
  script:
    - "git --version || exit 1"
    - "git clone https://oauth2:$ACCESS_TOKEN@gitlab.com/noritakaIzumi/my-portfolio-posts.git || exit 1"
    - "rm -rf my-portfolio-posts/.git || exit 1"
    - "mv my-portfolio-posts content || exit 1"
    - hugo --gc --ignoreCache
  artifacts:
    paths:
      - public
  only:
    - master
