baseURL: https://portfolio.fairy-select.com/

languageCode: en-us
title: "Fairy Select"
theme: "toha"

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
DefaultContentLanguage: en

# Allow raw html in markdown file
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: G-TCH9X4GKPZ

# Enable global emoji support
enableEmoji: true

# 日本語の文字数を正しく数える
hasCJKLanguage: true

# Custom parameters
params:
  # Background image of the landing page
  background: "/images/site/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://gitlab.com/noritakaIzumi/my-portfolio-posts
  gitForge: gitlab
  # Default branch of your Git repo
  gitBranch: master

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: false
        whatsapp: false
        email: false
        tumblr: false
        pocket: false
        diaspora: false
        mastodon: false
    # Enable & configure "Notes" features
    notes:
      enable: false
    # Enable comment feature. There, should be only one of them.
    comment:
      enable: true
      disqus:
        shortName: fairy-select
      # valine:
      #   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
      #   appKey: pVrT3C85KGIuk27t07eh6bUC
      #   avatar: retro
      #   placeholder: Share your thought.
      #   lang: en
      #   recordIP: true
      #   enableQQ: true
      # utteranc:
      #   repo: github.com/hugo-toha/hugo-toha.github.io
      #   issueTerm: title
      #   theme: github-light
    support:
      enable: true
      services:
        buymeacoffee:
          user: fairyselect
          text: よかったらジュースおごってください🥺

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # If you want to use different country flag for a language, specify them here.
  # flagOverwrites:
  # - languageCode: en
  #   countryCode: us

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
      # provider: mailchimp
      # mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true

  # Twitter cards.
  title: Fairy Select
  description: Portfolio and personal blog of Noritaka IZUMI.
  image: "images/author/man.png"
  twitterUser: "IzumiNoritaka"

  # Follow site title.
  subtitle: "My Portfolio"
  glue: " - "
